modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="satiscraftery"
version="0.0.1"
displayName="Satiscraftery"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Zhyov, MCreator"
description="Satisfactory ripoff for Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.satiscraftery]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.satiscraftery]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration